services:
  inventoryservice:
    build:
      context: ./InventoryService   # folder containing InventoryService's Dockerfile
    ports:
      - "8080:8080"                 # host:container - same as your manual -p flag
    env_file:
      - .env                       # Day 10: InventoryEventConsumer needs ServiceBus__ConnectionString too now

  orderservice:
    build:
      context: ./OrderService       # folder containing OrderService's Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - inventoryservice            # start-order only, not a readiness guarantee
    env_file:
      - .env                       # supplies ServiceBus__ConnectionString - never committed

  notificationservice:
    build:
      context: ./NotificationService
    ports:
      - "8082:8080"
    env_file:
      - .env                       # same Service Bus connection string, different subscription
